### ISSUE TITLE
Add the base code

### ISSUE THREAD

**Issue by SinaKhalili** [14000605/wiz-website#1]
We have decided to use a Vue + Django setup - comment tutorial please 😄

**Comment by Karan886** [comment]
Here is a link to a project setup we want: https://blog.gundammc.com/vue-js-django/

**Comment by Karan886** [comment]
Using https://github.com/NdagiStanley/vue-django to save us some set-up time. Details will be in the ReadMe shortly.

**Comment by Karan886** [comment]
All done.
